version: '3.8'

services:
  react-native:
    build: .
    ports:
      - "19000:19000"
    volumes:
      - .:/app
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    command: tail -f /dev/null